config/routes.rb
Rails.application.routes.draw do
  get 'poll_questions/index'  #Etsi pernaw auta pou den exv kanei scaffold!!!

  get 'results/ena'

  resources :results 

  resources :answers

  resources :questions

  resources :polls

  devise_for :users

  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/question.rb
class Question < ActiveRecord::Base


	belongs_to :user
    has_many :poll_questions, dependent: :destroy
	has_many :polls, :through => :poll_questions
	has_many :question_aswers, dependent: :destroy
	has_many :questions, :through => :question_aswers

    validates_presence_of :name
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def ena
    
  end


  def index
    if params[:poll_id]
      @questions = Question.where(:poll_id => params[:poll_id])
      @poll = Poll.find(params[:poll_id])
    else
      @questions = Question.all
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @poll = Poll.find(params[:poll_id]) #Pernw to param apo to submit button kai vriskw to poll
    @question.poll_id = @poll.id #Pernw to id tou poll pou vrika apo panw
    respond_to do |format|
      if @question.save
        PollQuestion.create(:poll_id => params[:poll_id], :question_id => @question.id)
        flash[:success] = 'Question was successfully created.'
        format.html { redirect_to @question }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name, :answer_number, :user_id, :poll_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <!--
  <div class="field">
    <%= f.label :answer_number %><br>
    <%= f.number_field :answer_number %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  
  <div class="field">
    <%= f.label :Dialekse_poll %><br>
    <%= f.collection_select(:poll_id, Poll.all, :id, :name) %>
  </div>
-->
  <div class="actions">
    <%= f.button :sumbit, name: "poll_id", value: params[:poll_id] %> <!--Apo pollindex paei se questionindex kai meta questionnew-->
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table class="table table-hover">
  <thead>
    <tr class='info'>
      <th>Name</th>
      <th>Answer number</th>
      <th>User</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %> <!-- Bazw where etsi wste na emfanizw ayta me id poll -->
      <tr>
        <td><%= link_to question.name, answers_path(:question_id => question.id)  %></td>
        <td><%= question.answer_number %></td>
        <td><%= question.user_id %></td>
        <td><%= question.poll_id %></td>
        <td><%= link_to 'Show', question, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_question_path(question), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- Pernaw to poll_id mesa po to link-->
<%= link_to new_question_path(:poll_id => params[:poll_id]), class: 'btn btn-success' do  %>
<i class="glyphicon glyphicon-plus"></i> New Question
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question.name %>
</p>

<p>
  <strong>Answer number:</strong>
  <%= @question.answer_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user_id %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @question.poll_id %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path(:poll_id => @question.poll_id) %>