config/routes.rb
Rails.application.routes.draw do
  get 'poll_questions/index'  #Etsi pernaw auta pou den exv kanei scaffold!!!

  get 'results/ena'

  resources :results 

  resources :answers

  resources :questions

  resources :polls

  devise_for :users

  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

	has_many :question_aswers
	has_many :questions, :through => :question_aswers

    validates_presence_of :name
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    if params[:question_id]
      @answers = Answer.where(:question_id => params[:question_id])
    else
      @answers = Answer.all 
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question_id = @question.id
    respond_to do |format|
      if @answer.save
        QuestionAswer.create(:question_id => params[:question_id], :answer_id => @answer.id)  #Lathos sto onoma tou modelou
        flash[:success] = 'Anser was successfully created.'
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:name, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <!--
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
-->
  <div class="actions">
    <%= f.button :sumbit, name: "question_id", value: params[:question_id] %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table class="table table-hover">
  <col width="2000">
  <col width="10">
  <col width="10">
  <col width="10">
  <thead>
    <tr class='info'>
      <th>Name</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.name %></td>
        <td><%= link_to 'Show', answer, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) , class: 'btn btn-info btn-xs'%></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_answer_path(:question_id => params[:question_id]), class: 'btn btn-success' do  %>
<i class="glyphicon glyphicon-plus"></i> New Answer
<% end %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path(:question_id => @answer.question_id) %>