config/routes.rb
Rails.application.routes.draw do
  get 'poll_questions/index'  #Etsi pernaw auta pou den exv kanei scaffold!!!

  get 'results/ena'

  resources :results 

  resources :answers

  resources :questions

  resources :polls

  devise_for :users

  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base
    
    has_many :poll_questions
	has_many :questions, :through => :poll_questions
	belongs_to :user

	validates_uniqueness_of :name
    validates_presence_of :name


end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :update, :destroy]

  def check_auth
    if current_user.id != @poll.user_id
      flash[:notice] = "Sorry you can't edit this poll"
      redirect_to(polls_path)
    end
    
  end

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    @poll.user_id = current_user.id
    respond_to do |format|
      if @poll.save
        flash[:success] = 'Poll was successfully created.'
        format.html { redirect_to @poll }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        flash[:success] = 'Poll was successfully updated.'
        format.html { redirect_to @poll }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      flash[:success] = 'Poll was successfully destroyed'
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :question_number)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <i class="icon-ok icon-white"></i> Save
    <% end %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<% if current_user.try(:admin?) %>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', polls_path %></li>
  <li><%= link_to 'New todo', new_poll_path %></li>
</ul>


<table class="table table-hover" >
  <col width="2000">
  <col width="10">
  <col width="10">
  <col width="10">
  <col width="10">
  <thead>
    <tr class='info'>
      <th>Name</th>
      <th></th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.name, questions_path(:poll_id => poll.id) %></td> <!-- pernaw to poll.id sto question index -->
        <td><%= link_to 'Show', poll, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-xs'%></td>
        <td><%= link_to 'Take this survey', new_result_path(:poll_id => poll.id), class: 'btn btn-warning btn-xs'%></td>
        <td><%= link_to 'Apotelesmata', results_path(:poll_id => poll.id), class: 'btn btn-warning btn-xs'%></td>

        <!-- <td> link se view pou tha apantw se erwtiseis. Tha kanw nea view pou tha pernw dedomena kai tha ta apothikeuw </td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %>

<table class="table table-hover" >
  <col width="2000">
  <col width="10">
  <col width="10">
  <col width="10">
  <col width="10">
  <thead>
    <tr class='info'>
      <th>Name</th>
      <th></th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.name %></td>
        <td><%= poll.question_number %></td>
        <td><%= link_to 'Show', poll, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Take this survey', new_result_path(:poll_id => poll.id), class: 'btn btn-warning btn-xs' %></td>
        <td><%= link_to 'Apotelesmata', results_path(:poll_id => poll.id), class: 'btn btn-warning btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end %>

<% if current_user.try(:admin?) %>

<%= link_to new_poll_path, class: 'btn btn-success' do  %>
<i class="glyphicon glyphicon-plus"></i> New Poll
<% end %>

<% end %>

app/views/polls/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li ><%= link_to 'View list', polls_path %></li>
  <li class="active"><%= link_to 'New todo', new_poll_path %></li>
</ul>

<h1>New poll</h1>

<%= render 'form' %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poll.name %>
</p>



<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>